"""Protocols isolating the workflow from external systems."""
from __future__ import annotations
from typing import Protocol
from automation.domain.models import ActionPlan, ConfirmationRecord, Preview, UserRequest

class Planner(Protocol):
    def plan(self, request: UserRequest, source_text: str) -> tuple[ActionPlan, Preview]: ...
class PlanRepository(Protocol):
    def save(self, plan: ActionPlan, preview: Preview) -> None: ...
    def get(self, plan_id: str) -> tuple[ActionPlan, Preview]: ...
    def claim(self, confirmation: ConfirmationRecord) -> ActionPlan: ...
class ArtifactStore(Protocol):
    def read_text(self, artifact_id: str) -> str: ...
    def create_output(self, name: str, media_type: str, content: bytes): ...
